export enum CardValue {
  Ace = 'A',
  Two = '2',
  Three = '3',
  Four = '4',
  Five = '5',
  Six = '6',
  Seven = '7',
  Eight = '8',
  Nine = '9',
  Ten = '10',
  Jack = 'J',
  Queen = 'Q',
  King = 'K',
}

export const CARD_RANKS: CardValue[] = [
  CardValue.Two,
  CardValue.Three,
  CardValue.Four,
  CardValue.Five,
  CardValue.Six,
  CardValue.Seven,
  CardValue.Eight,
  CardValue.Nine,
  CardValue.Ten,
  CardValue.Jack,
  CardValue.Queen,
  CardValue.King,
  CardValue.Ace,
];
